AgencyWeb/Areas/Functions/Controllers/ClaimReportController.cs
using AgencyWeb.Areas.BaseController;
using AgencyWeb.Areas.Functions.Models;
using AgencyWeb.Services;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Diagnostics;

namespace AgencyWeb.Areas.Functions.Controllers
{
    [Route("[area]/[controller]")]

    public class ClaimReportController : BaseFunctionController
    {
        private readonly IApiService _apiService;

        public ClaimReportController(IApiService apiService)
        {
            _apiService = apiService;
        }
        [HttpGet("[action]")]
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }
        [HttpGet("[action]")]
        public IActionResult List()
        {
            return View();
        }
        [HttpGet("[action]/{id}")]
        public IActionResult Detail(long id)
        {
            var _response = model.Where(p => p.ClaimReportId == id).First();
            return View(_response);
        }

        [HttpGet("[action]")]
        public object GetList(DataSourceLoadOptions loadOptions)
        {
            var _response = model;

            return DataSourceLoader.Load(_response, loadOptions);
        }

        public static List<ClaimReportDto> model = new List<ClaimReportDto>()
        {
            new ClaimReportDto
            {
                ClaimReportId = 1,
                Policy = "HĐ-7737",
                ClaimNumber = "QLBH-34534",
                LifeAssured = "Phạm Văn Hai",
                ClaimBenefit = "Chi trả tai nạn",
                EventDate = DateTime.Now,
                ClaimApprovedAmount = 75000000,
                ClaimStatus = "Được duyệt",
                Notification = "Thông báo",
                DateOfClaimSubmission = DateTime.Now,
                DateOfSupplementingDocuments = DateTime.Now,
                DateOfDecision = DateTime.Now,
                Agent = "Nguyễn Văn A - 4234",
            },
            new ClaimReportDto
            {
                ClaimReportId = 2,
                Policy = "HĐ-4353",
                ClaimNumber = "QLBH-53823",
                LifeAssured = "Phạm Văn Hai",
                ClaimBenefit = "Chi trả tai nạn",
                EventDate = DateTime.Now,
                ClaimApprovedAmount = 45000000,
                ClaimStatus = "Được duyệt",
                Notification = "Thông báo",
                DateOfClaimSubmission = DateTime.Now,
                DateOfSupplementingDocuments = DateTime.Now,
                DateOfDecision = DateTime.Now,
                Agent = "Nguyễn Văn A - 4234",
            },
            new ClaimReportDto
            {
                ClaimReportId = 3,
                Policy = "HĐ-653345",
                ClaimNumber = "QLBH-978056",
                LifeAssured = "Phạm Văn Hai",
                ClaimBenefit = "Chi trả tai nạn",
                EventDate = DateTime.Now,
                ClaimApprovedAmount = 35000000,
                ClaimStatus = "Được duyệt",
                Notification = "Thông báo",
                DateOfClaimSubmission = DateTime.Now,
                DateOfSupplementingDocuments = DateTime.Now,
                DateOfDecision = DateTime.Now,
                Agent = "Nguyễn Văn A - 4234",
            },

        };
    }
}

AgencyWeb/Areas/Functions/Views/ClaimReport/Detail.cshtml
@using AgencyWeb.Areas.Functions.Controllers;
@using AgencyWeb.Models
@using AgencyWeb.Areas.BusinessIndicators.Controllers
@using Microsoft.AspNetCore.Mvc.Localization
@model ClaimReportDto

@inject IHtmlLocalizer<ClaimReportDto> HtmlLocalizer

@{
    var confirmDeleteMessage = String.Format(@HtmlLocalizer["ConfirmDeleteMessage"].Value);
    var confirmDeleteTitle = String.Format(@HtmlLocalizer["ConfirmDeleteTitle"].Value);
}

<div class="container-fluid p-0">
   @*  <h1 class="h5 mb-3 form-title">
        Danh sách TVTC
        <i class="fa fa-caret-right" aria-none="true"></i>
        <strong>Hỗ sơ TVTC</strong>
    </h1> *@
    <div class="row">
        <div class="col-12 col-md-12 col-xxl-6 d-flex order-3 order-xxl-2">
            <div class="card card-body form-control-ui">
                <p>
                    <a class="form-title" data-bs-toggle="collapse" href="#collapse01" role="button" aria-expanded="false" aria-controls="collapseExample">
                        <strong>Chi tiết yêu cầu giải quyết quyền lợi bảo hiểm</strong>
                    </a>
                </p>
                <div class="collapse show" id="collapse01">
                    <div class="row">
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().TextBox()
                                    .ElementAttr("class", "required-validation")
                                    .Label("Hợp đồng bảo hiểm").LabelMode(EditorLabelMode.Floating)
                                    .MaxLength(100).Value(Model.Policy).ReadOnly(true))
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().TextBox()
                                    .ElementAttr("class", "required-validation")
                                    .Label("Số yêu cầu QLBH").LabelMode(EditorLabelMode.Floating)
                                    .MaxLength(100).Value(Model.ClaimNumber).ReadOnly(true))
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().TextBox()
                                    .ElementAttr("class", "required-validation")
                                    .Label("Người được bảo hiểm").LabelMode(EditorLabelMode.Floating)
                                    .MaxLength(100).Value(Model.LifeAssured).ReadOnly(true))
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().TextBox()
                                    .ElementAttr("class", "required-validation")
                                    .Label("Quyền lợi bảo hiểm").LabelMode(EditorLabelMode.Floating)
                                    .MaxLength(100).Value(Model.ClaimBenefit).ReadOnly(true))
                            </div>
                        </div>
                        
                        
                         <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().DateBox()
                                    .Type(DateBoxType.Date)
                                    .DisplayFormat("dd/MM/yyyy")
                                    .UseMaskBehavior(true)
                                    .Placeholder("dd/mm/yyyy")
                                    .Value(Model.EventDate)
                                    .Label("Ngày xảy ra sự kiện bảo hiểm").LabelMode(EditorLabelMode.Floating)
                                    .ElementAttr("class", "required-validation").ShowClearButton(true)
                                    .ReadOnly(true)
                                    )
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().NumberBox()
                                    .ElementAttr("class", "required-validation")
                                    .Label("Số tiền chấp nhận chi trả").LabelMode(EditorLabelMode.Floating)
                                    .Value(Model.ClaimApprovedAmount).ReadOnly(true))
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().TextBox()
                                    .ElementAttr("class", "required-validation")
                                    .Label("Tình trạng yêu cầu QLBH").LabelMode(EditorLabelMode.Floating)
                                    .MaxLength(100).Value(Model.ClaimStatus).ReadOnly(true))
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().TextBox()
                                    .ElementAttr("class", "required-validation")
                                    .Label("Thư thông báo").LabelMode(EditorLabelMode.Floating)
                                    .MaxLength(100).Value(Model.Notification).ReadOnly(true))
                            </div>
                        </div>


                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().DateBox()
                                    .Type(DateBoxType.Date)
                                    .DisplayFormat("dd/MM/yyyy")
                                    .UseMaskBehavior(true)
                                    .Placeholder("dd/mm/yyyy")
                                    .Value(Model.DateOfClaimSubmission)
                                    .Label("Ngày yêu cầu QLBH").LabelMode(EditorLabelMode.Floating)
                                    .ElementAttr("class", "required-validation").ShowClearButton(true)
                                    .ReadOnly(true)
                                    )
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().DateBox()
                                    .Type(DateBoxType.Date)
                                    .DisplayFormat("dd/MM/yyyy")
                                    .UseMaskBehavior(true)
                                    .Placeholder("dd/mm/yyyy")
                                    .Value(Model.DateOfSupplementingDocuments)
                                    .Label("Ngày bổ sung thông tin").LabelMode(EditorLabelMode.Floating)
                                    .ElementAttr("class", "required-validation").ShowClearButton(true)
                                    .ReadOnly(true)
                                    )
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().DateBox()
                                    .Type(DateBoxType.Date)
                                    .DisplayFormat("dd/MM/yyyy")
                                    .UseMaskBehavior(true)
                                    .Placeholder("dd/mm/yyyy")
                                    .Value(Model.DateOfDecision)
                                    .Label("Ngày ra quyết định").LabelMode(EditorLabelMode.Floating)
                                    .ElementAttr("class", "required-validation").ShowClearButton(true)
                                    .ReadOnly(true)
                                    )
                            </div>
                        </div>
                        

                         <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="form-group">
                                @(Html.DevExtreme().TextBox()
                                    .ElementAttr("class", "required-validation")
                                    .Label("TVTC").LabelMode(EditorLabelMode.Floating)
                                    .MaxLength(100).Value(Model.Agent).ReadOnly(true))
                            </div>
                        </div>
                         
                    </div>
                </div>
                <div class="row button-search-row">
                    <div class="col-md-12">
                        <button class="btn btn-purple-style" type="submit" onclick="onBackToAgentListClicked()"><span class="glyphicon glyphicon-triangle-left"></span> Trở về</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    function onBackToAgentListClicked() {
        location.href = '@Url.Action("List", "ClaimReport", new { area = "Functions" })';
    }  
</script>